// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://myeyvmluscudiheijdrq.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im15ZXl2bWx1c2N1ZGloZWlqZHJxIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDU4NjE4MzksImV4cCI6MjA2MTQzNzgzOX0.kNd2QP6DaRIhmwsIjQZIZAtgc1QfaWgZAmuY-dgrLYw";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);